-- MySQL schema + seed for the dialect-compat tests. MySQL doesn't support
-- "GENERATED BY DEFAULT AS IDENTITY" (SQL:2003 syntax) — use AUTO_INCREMENT
-- which is MySQL's equivalent. The application code (mapper queries) doesn't
-- care about the difference; this is purely a DDL convention split.
CREATE TABLE IF NOT EXISTS test_users (
    id         BIGINT AUTO_INCREMENT PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    created_at TIMESTAMP    NOT NULL
);

INSERT INTO test_users (name, created_at) VALUES
  ('alice',   '2026-05-01 10:00:00'),
  ('bob',     '2026-05-01 10:01:00'),
  ('charlie', '2026-05-01 10:02:00'),
  ('dave',    '2026-05-01 10:03:00'),
  ('eve',     '2026-05-01 10:04:00'),
  ('frank',   '2026-05-01 10:05:00'),
  ('grace',   '2026-05-01 10:06:00'),
  ('heidi',   '2026-05-01 10:07:00'),
  ('ivan',    '2026-05-01 10:08:00'),
  ('judy',    '2026-05-01 10:09:00'),
  ('mallory', '2026-05-01 10:10:00'),
  ('niaj',    '2026-05-01 10:11:00'),
  ('olivia',  '2026-05-01 10:12:00'),
  ('peggy',   '2026-05-01 10:13:00'),
  ('quentin', '2026-05-01 10:14:00');
