-- PostgreSQL schema + seed for the dialect-compat tests. Single file so it
-- can be passed to PostgreSQLContainer.withInitScript(...) which only takes
-- one resource. Uses PostgreSQL's GENERATED BY DEFAULT AS IDENTITY (Postgres
-- 10+) — that matches the H2 schema syntax, but the underlying behaviour is
-- the real PostgreSQL sequence implementation.
CREATE TABLE IF NOT EXISTS test_users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    created_at TIMESTAMP    NOT NULL
);

INSERT INTO test_users (name, created_at) VALUES
  ('alice',   '2026-05-01 10:00:00'),
  ('bob',     '2026-05-01 10:01:00'),
  ('charlie', '2026-05-01 10:02:00'),
  ('dave',    '2026-05-01 10:03:00'),
  ('eve',     '2026-05-01 10:04:00'),
  ('frank',   '2026-05-01 10:05:00'),
  ('grace',   '2026-05-01 10:06:00'),
  ('heidi',   '2026-05-01 10:07:00'),
  ('ivan',    '2026-05-01 10:08:00'),
  ('judy',    '2026-05-01 10:09:00'),
  ('mallory', '2026-05-01 10:10:00'),
  ('niaj',    '2026-05-01 10:11:00'),
  ('olivia',  '2026-05-01 10:12:00'),
  ('peggy',   '2026-05-01 10:13:00'),
  ('quentin', '2026-05-01 10:14:00');
